"""Build a Markdown validation report for the Kerr s=0 spectral solver."""

import csv
import os
import sys


ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SUMMARY = os.path.join(ROOT, "results", "kerr_scalar_adaptive_summary.csv")
SWEEP = os.path.join(ROOT, "results", "kerr_scalar_frequency_sweep.csv")
REPORT = os.path.join(ROOT, "docs", "kerr_scalar_validation_report.md")


def fmt(x):
    return f"{float(x):.3e}"


def main():
    if not os.path.exists(SUMMARY):
        raise FileNotFoundError(
            f"{SUMMARY} not found. Run scripts/adaptive_kerr_scalar_gsn_validation.py first."
        )

    with open(SUMMARY, newline="") as f:
        rows = list(csv.DictReader(f))

    max_score = max(float(row["score"]) for row in rows)
    max_flux = max(float(row["flux_balance_error"]) for row in rows)
    all_passed = all(row["passed"] == "true" for row in rows)
    sweep_rows = []
    if os.path.exists(SWEEP):
        with open(SWEEP, newline="") as f:
            sweep_rows = list(csv.DictReader(f))

    lines = [
        "# Kerr s=0 spectral validation report",
        "",
        "## Scope",
        "",
        "This report validates the two-domain Chebyshev spectral solver for the scalar",
        "Teukolsky in mode on Kerr. The solver uses `z = r_+/r`, direct endpoint",
        "collocation at `z=0,1`, degenerate endpoint ODE rows as regularity",
        "conditions, and value/derivative matching at an intermediate radius.",
        "",
        "The external benchmark is `GeneralizedSasakiNakamura.jl` with the",
        "`UNIT_TEUKOLSKY_TRANS` convention, so `B_trans = 1` at the horizon.",
        "",
        "## Acceptance gates",
        "",
        "- `rel_abs_B_inc <= 1e-7`",
        "- `rel_abs_B_ref <= 1e-7`",
        "- `flux_balance_error <= 1e-8`",
        "",
        "Only amplitude magnitudes and flux balance are used as pass/fail quantities.",
        "The complex amplitudes include convention-dependent phase factors from the",
        "additive constant in `r*` and package-specific normalization choices; those",
        "phase factors are recorded in the CSV output but are not used as invariant",
        "benchmark errors.",
        "",
        "## Summary",
        "",
        f"- Cases tested: {len(rows)}",
        f"- All cases passed: `{str(all_passed).lower()}`",
        f"- Worst score: `{max_score:.3e}`",
        f"- Worst flux-balance residual: `{max_flux:.3e}`",
        "",
        "| l | m | a | omega | N | r_match | mapping | rel_abs_B_inc | rel_abs_B_ref | flux | score | passed |",
        "|---:|---:|---:|---:|---:|---:|:---|---:|---:|---:|---:|:---|",
    ]

    for row in rows:
        lines.append(
            "| {l} | {m} | {a:.3g} | {omega:.3g} | {N} | {r_match:.3g} | "
            "{mapping} | {rel_inc} | {rel_ref} | {flux} | {score} | {passed} |".format(
                l=row["l"],
                m=row["m"],
                a=float(row["a"]),
                omega=float(row["omega"]),
                N=row["N"],
                r_match=float(row["r_match"]),
                mapping=row["mapping"],
                rel_inc=fmt(row["rel_abs_B_inc"]),
                rel_ref=fmt(row["rel_abs_B_ref"]),
                flux=fmt(row["flux_balance_error"]),
                score=fmt(row["score"]),
                passed=row["passed"],
            )
        )

    if sweep_rows:
        max_sweep_score = max(float(row["score"]) for row in sweep_rows)
        max_sweep_flux = max(float(row["flux_balance_error"]) for row in sweep_rows)
        all_sweep_passed = all(row["passed"] == "true" for row in sweep_rows)
        superradiant_rows = [
            row for row in sweep_rows
            if row["superradiant"] == "true" and float(row["amplification"]) > 0.0
        ]
        max_amp = (
            max(superradiant_rows, key=lambda row: float(row["amplification"]))
            if superradiant_rows else None
        )

        lines.extend([
            "",
            "## Frequency sweep",
            "",
            "A publication-style frequency sweep is generated by",
            "`scripts/run_kerr_scalar_frequency_sweep.py` and plotted by",
            "`scripts/plot_kerr_scalar_frequency_sweep.py`. The sweep uses",
            "self-convergence in spectral order, the same direct endpoint rows, and",
            "the invariant flux balance check.",
            "",
            f"- Sweep points: {len(sweep_rows)}",
            f"- All sweep points passed: `{str(all_sweep_passed).lower()}`",
            f"- Worst sweep score: `{max_sweep_score:.3e}`",
            f"- Worst sweep flux-balance residual: `{max_sweep_flux:.3e}`",
            "- Maximum sampled superradiant amplification: " + (
                f"`{float(max_amp['amplification']):.3e}` at "
                f"`{max_amp['label']}`, `omega={float(max_amp['omega']):.3g}`"
                if max_amp is not None else "`none in this sweep`"
            ),
            "",
            "| label | l | m | a | omega range | points | max R-1 | all passed |",
            "|:---|---:|---:|---:|:---|---:|---:|:---|",
        ])

        for label in sorted({row["label"] for row in sweep_rows}):
            subset = [row for row in sweep_rows if row["label"] == label]
            omegas = [float(row["omega"]) for row in subset]
            max_case_amp = max(float(row["amplification"]) for row in subset)
            case_passed = all(row["passed"] == "true" for row in subset)
            first = subset[0]
            lines.append(
                "| {label} | {l} | {m} | {a:.3g} | {omin:.3g}--{omax:.3g} | "
                "{n} | {amp:.3e} | {passed} |".format(
                    label=label,
                    l=first["l"],
                    m=first["m"],
                    a=float(first["a"]),
                    omin=min(omegas),
                    omax=max(omegas),
                    n=len(subset),
                    amp=max_case_amp,
                    passed=str(case_passed).lower(),
                )
            )

    lines.extend([
        "",
        "## Current interpretation",
        "",
        "The present validation covers the Schwarzschild limit, moderate Kerr spin,",
        "near-superradiant scalar modes, low-frequency superradiant scattering,",
        "high-frequency small-reflection scattering, and high-spin Kerr cases.",
        "",
        "The worst invariant benchmark error in the current table is below `1.5e-8`,",
        "which is comfortably inside the `1e-7` amplitude-magnitude target. The",
        "hardest case is the high-frequency `l=m=2, a=0.5, omega=1.0` mode, where",
        "`B_ref` is small and therefore relative errors are more sensitive to",
        "conditioning.",
        "",
        "The frequency sweep resolves the Schwarzschild absorption curve and the",
        "Kerr scalar superradiant regime. For the sampled rotating cases, `R > 1`",
        "appears only for `omega < m Omega_H`, while the reported flux residuals",
        "remain below the acceptance gate.",
        "",
        "## Remaining PRD-level work",
        "",
        "- Expand the GSN benchmark grid before using final production tables.",
        "- Densify the production frequency grid around each superradiant threshold.",
        "- State the complex phase convention explicitly if phase-sensitive",
        "  observables are reported.",
        "- Carry the nonlinear Green-function correction over from the Schwarzschild",
        "  project only after the linear solver validation remains stable on a denser",
        "  grid.",
        "",
        "Generated from `results/kerr_scalar_adaptive_summary.csv` and, when",
        "available, `results/kerr_scalar_frequency_sweep.csv`.",
        "",
    ])

    os.makedirs(os.path.dirname(REPORT), exist_ok=True)
    with open(REPORT, "w", encoding="utf-8", newline="\n") as f:
        f.write("\n".join(lines))
    print(REPORT)


if __name__ == "__main__":
    main()
